name: Start_Stream

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform (youtube or restream)'
        required: true
        default: 'youtube'
        type: choice
        options:
          - youtube
          - restream
      channel_name:
        description: 'Kick Channel Name'
        required: true
        type: string
      stream_key:
        description: 'Stream Key'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Run Stream Script
        env:
          PLATFORM: ${{ inputs.platform }}
          CHANNEL_NAME: ${{ inputs.channel_name }}
          STREAM_KEY: ${{ inputs.stream_key }}
        run: |
          python main.py
